
export const GET_POST_LIST = "GET_POST_LIST";
export type GET_POST_LIST = typeof GET_POST_LIST;

export const RESPONSE_POST_LIST = "RESPONSE_POST_LIST";
export type RESPONSE_POST_LIST = typeof RESPONSE_POST_LIST;

export const GET_POST_DETAIL = "GET_POST_DETAIL";
export type GET_POST_DETAIL = typeof GET_POST_DETAIL;

export const RESPONSE_POST_DETAIL = "RESPONSE_POST_DETAIL";
export type RESPONSE_POST_DETAIL = typeof RESPONSE_POST_DETAIL;



export const GET_CATEGORY= "GET_CATEGORY";
export type GET_CATEGORY = typeof GET_CATEGORY;

export const RESPONSE_CATEGORY = "RESPONSE_CATEGORY";
export type RESPONSE_CATEGORY = typeof RESPONSE_CATEGORY;


export const GET_CATEGORY_POSTS= "GET_CATEGORY_POSTS";
export type GET_CATEGORY_POSTS = typeof GET_CATEGORY_POSTS;

export const RESPONSE_CATEGORY_POSTS = "RESPONSE_CATEGORY_POSTS";
export type RESPONSE_CATEGORY_POSTS = typeof RESPONSE_CATEGORY_POSTS;
