
export const GET_POST_LIST = "GET_POST_LIST";
export type GET_POST_LIST = typeof GET_POST_LIST;

export const RESPONSE_POST_LIST = "RESPONSE_POST_LIST";
export type RESPONSE_POST_LIST = typeof RESPONSE_POST_LIST;

export const GET_POST_DETAIL = "GET_POST_DETAIL";
export type GET_POST_DETAIL = typeof GET_POST_DETAIL;

export const RESPONSE_POST_DETAIL = "RESPONSE_POST_DETAIL";
export type RESPONSE_POST_DETAIL = typeof RESPONSE_POST_DETAIL;
